import { normalize } from "@/lib/quiz";
import manifest from "@/public/audio/manifest.json";

// Generated by `npm run gen:audio` — maps a normalized Indonesian phrase to a
// bundled mp3 filename under /public/audio. Empty until audio is generated.
const map: Record<string, string> = manifest as Record<string, string>;

export function audioFileFor(text: string): string | null {
  return map[normalize(text)] ?? null;
}

export function hasBundledAudio(): boolean {
  return Object.keys(map).length > 0;
}
